### ISSUE TITLE
Is this still active?

### ISSUE THREAD

**Issue by giannissc** [hmeyer/implicit3d#1]

**Comment by hmeyer** [comment]
Kind of. I'm working on it as part of https://github.com/hmeyer/truescad.
These days I'm only adding new features when the need arises.
Are you interested in collaborating, using or contributing?

**Comment by giannissc** [comment]
I would actually what would be the best place to start? Are there any examples I could play with or some documentation I could read?

**Comment by hmeyer** [comment]
I'd suggest cloning https://github.com/hmeyer/truescad and trying to build it (cargo build --release).
Then you can open the example file (xplicit.scad).
I guess I should really write some documentation.... (also happy to review PRs).
